url: http://mrelectron.github.com
title: Heterodoxic
subtitle: Man will never be free until the last king is strangled with the entrails of the last priest
author: Mia
simple_search: http://google.com/search

date_format: "ordinal"
subscribe_rss: /atom.xml
subscribe_email:
email:
root: /
permalink: /blog/:year/:month/:day/:title/
source: source
destination: public
plugins: plugins
code_dir: downloads/code
category_dir: blog/categories
markdown: rdiscount
pygments: false

paginate: 10
pagination_dir: blog
recent_posts: 5
excerpt_link: "Read on &rarr;"

titlecase: true
default_asides: [asides/recent_posts.html, asides/github.html, asides/twitter.html, asides/delicious.html, asides/pinboard.html, asides/googleplus.html]
github_user:
github_repo_count: 0
github_show_profile_link: true
github_skip_forks: true

twitter_user:
twitter_tweet_count: 4
twitter_show_replies: false
twitter_follow_button: true
twitter_show_follower_count: false
twitter_tweet_button: true

google_plus_one: true
google_plus_one_size: medium

googleplus_user:
googleplus_hidden: false

pinboard_user:
pinboard_count: 3

delicious_user:
delicious_count: 3

disqus_short_name:
disqus_show_comment_count: false

google_analytics_tracking_id:

facebook_like: true   
