url: http://mrelectron.github.com
title: heterodoxic
subtitle: Man will never be free until the last king is strangled with the entrails of the last priest
author: MAB
simple_search: http://google.com/search

lsi: true
date_format: "ordinal"
subscribe_rss: /atom.xml
subscribe_email:
email:
root: /
permalink: /blog/:year/:month/:day/:title/
source: source
destination: public
plugins: plugins
code_dir: downloads/code
category_dir: blog/categories
markdown: rdiscount
pygments: false

paginate: 10
pagination_dir: blog
recent_posts: 15
excerpt_link: "Read on &rarr;"

titlecase: true
default_asides: [asides/recent_posts.html, custom/asides/related.html, custom/asides/category_list.html custom/asides/tag_cloud.html]
github_user:
github_repo_count: 0
github_show_profile_link: true
github_skip_forks: true

twitter_user:
twitter_tweet_count: 4
twitter_show_replies: false
twitter_follow_button: false
twitter_show_follower_count: false
twitter_tweet_button: false

google_plus_one: false
google_plus_one_size: medium

googleplus_user:
googleplus_hidden: true

pinboard_user:
pinboard_count: 3

delicious_user:
delicious_count: 3

disqus_short_name:
disqus_show_comment_count: false

google_analytics_tracking_id:

facebook_like: false
